[build]
    command = "pnpm run build"
    ignore = 'test "$BRANCH" = "main" && git log -1 --pretty=%s "$COMMIT_REF" | grep -q "^chore: bump version to "'
    publish = "dist/client"

[dev]
    command = "pnpm dev"
    framework = "#custom"
    targetPort = 3000
    port = 8888
    publish = "dist/client"
