/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as FundraisingRouteImport } from './routes/fundraising'
import { Route as CubsRouteImport } from './routes/cubs'
import { Route as BeaversRouteImport } from './routes/beavers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as AboutUsHutRenovationRouteImport } from './routes/about-us/hut-renovation'
import { Route as AboutUsFaqRouteImport } from './routes/about-us/faq'
import { Route as AboutUsDocumentationRouteImport } from './routes/about-us/documentation'
import { Route as AboutUsContactRouteImport } from './routes/about-us/contact'
import { Route as AboutUsBookingsRouteImport } from './routes/about-us/bookings'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1ContactRouteImport } from './routes/api/v1/contact'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingRoute = FundraisingRouteImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const CubsRoute = CubsRouteImport.update({
  id: '/cubs',
  path: '/cubs',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaversRoute = BeaversRouteImport.update({
  id: '/beavers',
  path: '/beavers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsHutRenovationRoute = AboutUsHutRenovationRouteImport.update({
  id: '/about-us/hut-renovation',
  path: '/about-us/hut-renovation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsFaqRoute = AboutUsFaqRouteImport.update({
  id: '/about-us/faq',
  path: '/about-us/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsDocumentationRoute = AboutUsDocumentationRouteImport.update({
  id: '/about-us/documentation',
  path: '/about-us/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsContactRoute = AboutUsContactRouteImport.update({
  id: '/about-us/contact',
  path: '/about-us/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsBookingsRoute = AboutUsBookingsRouteImport.update({
  id: '/about-us/bookings',
  path: '/about-us/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContactRoute = ApiV1ContactRouteImport.update({
  id: '/api/v1/contact',
  path: '/api/v1/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beavers': typeof BeaversRoute
  '/cubs': typeof CubsRoute
  '/fundraising': typeof FundraisingRoute
  '/scouts': typeof ScoutsRoute
  '/shop': typeof ShopRoute
  '/volunteer': typeof VolunteerRoute
  '/about-us/bookings': typeof AboutUsBookingsRoute
  '/about-us/contact': typeof AboutUsContactRoute
  '/about-us/documentation': typeof AboutUsDocumentationRoute
  '/about-us/faq': typeof AboutUsFaqRoute
  '/about-us/hut-renovation': typeof AboutUsHutRenovationRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/api/v1/contact': typeof ApiV1ContactRoute
  '/api/v1/health': typeof ApiV1HealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beavers': typeof BeaversRoute
  '/cubs': typeof CubsRoute
  '/fundraising': typeof FundraisingRoute
  '/scouts': typeof ScoutsRoute
  '/shop': typeof ShopRoute
  '/volunteer': typeof VolunteerRoute
  '/about-us/bookings': typeof AboutUsBookingsRoute
  '/about-us/contact': typeof AboutUsContactRoute
  '/about-us/documentation': typeof AboutUsDocumentationRoute
  '/about-us/faq': typeof AboutUsFaqRoute
  '/about-us/hut-renovation': typeof AboutUsHutRenovationRoute
  '/about-us': typeof AboutUsIndexRoute
  '/api/v1/contact': typeof ApiV1ContactRoute
  '/api/v1/health': typeof ApiV1HealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beavers': typeof BeaversRoute
  '/cubs': typeof CubsRoute
  '/fundraising': typeof FundraisingRoute
  '/scouts': typeof ScoutsRoute
  '/shop': typeof ShopRoute
  '/volunteer': typeof VolunteerRoute
  '/about-us/bookings': typeof AboutUsBookingsRoute
  '/about-us/contact': typeof AboutUsContactRoute
  '/about-us/documentation': typeof AboutUsDocumentationRoute
  '/about-us/faq': typeof AboutUsFaqRoute
  '/about-us/hut-renovation': typeof AboutUsHutRenovationRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/api/v1/contact': typeof ApiV1ContactRoute
  '/api/v1/health': typeof ApiV1HealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beavers'
    | '/cubs'
    | '/fundraising'
    | '/scouts'
    | '/shop'
    | '/volunteer'
    | '/about-us/bookings'
    | '/about-us/contact'
    | '/about-us/documentation'
    | '/about-us/faq'
    | '/about-us/hut-renovation'
    | '/about-us/'
    | '/api/v1/contact'
    | '/api/v1/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beavers'
    | '/cubs'
    | '/fundraising'
    | '/scouts'
    | '/shop'
    | '/volunteer'
    | '/about-us/bookings'
    | '/about-us/contact'
    | '/about-us/documentation'
    | '/about-us/faq'
    | '/about-us/hut-renovation'
    | '/about-us'
    | '/api/v1/contact'
    | '/api/v1/health'
  id:
    | '__root__'
    | '/'
    | '/beavers'
    | '/cubs'
    | '/fundraising'
    | '/scouts'
    | '/shop'
    | '/volunteer'
    | '/about-us/bookings'
    | '/about-us/contact'
    | '/about-us/documentation'
    | '/about-us/faq'
    | '/about-us/hut-renovation'
    | '/about-us/'
    | '/api/v1/contact'
    | '/api/v1/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeaversRoute: typeof BeaversRoute
  CubsRoute: typeof CubsRoute
  FundraisingRoute: typeof FundraisingRoute
  ScoutsRoute: typeof ScoutsRoute
  ShopRoute: typeof ShopRoute
  VolunteerRoute: typeof VolunteerRoute
  AboutUsBookingsRoute: typeof AboutUsBookingsRoute
  AboutUsContactRoute: typeof AboutUsContactRoute
  AboutUsDocumentationRoute: typeof AboutUsDocumentationRoute
  AboutUsFaqRoute: typeof AboutUsFaqRoute
  AboutUsHutRenovationRoute: typeof AboutUsHutRenovationRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  ApiV1ContactRoute: typeof ApiV1ContactRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising': {
      id: '/fundraising'
      path: '/fundraising'
      fullPath: '/fundraising'
      preLoaderRoute: typeof FundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cubs': {
      id: '/cubs'
      path: '/cubs'
      fullPath: '/cubs'
      preLoaderRoute: typeof CubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beavers': {
      id: '/beavers'
      path: '/beavers'
      fullPath: '/beavers'
      preLoaderRoute: typeof BeaversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/hut-renovation': {
      id: '/about-us/hut-renovation'
      path: '/about-us/hut-renovation'
      fullPath: '/about-us/hut-renovation'
      preLoaderRoute: typeof AboutUsHutRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/faq': {
      id: '/about-us/faq'
      path: '/about-us/faq'
      fullPath: '/about-us/faq'
      preLoaderRoute: typeof AboutUsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/documentation': {
      id: '/about-us/documentation'
      path: '/about-us/documentation'
      fullPath: '/about-us/documentation'
      preLoaderRoute: typeof AboutUsDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/contact': {
      id: '/about-us/contact'
      path: '/about-us/contact'
      fullPath: '/about-us/contact'
      preLoaderRoute: typeof AboutUsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/bookings': {
      id: '/about-us/bookings'
      path: '/about-us/bookings'
      fullPath: '/about-us/bookings'
      preLoaderRoute: typeof AboutUsBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contact': {
      id: '/api/v1/contact'
      path: '/api/v1/contact'
      fullPath: '/api/v1/contact'
      preLoaderRoute: typeof ApiV1ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeaversRoute: BeaversRoute,
  CubsRoute: CubsRoute,
  FundraisingRoute: FundraisingRoute,
  ScoutsRoute: ScoutsRoute,
  ShopRoute: ShopRoute,
  VolunteerRoute: VolunteerRoute,
  AboutUsBookingsRoute: AboutUsBookingsRoute,
  AboutUsContactRoute: AboutUsContactRoute,
  AboutUsDocumentationRoute: AboutUsDocumentationRoute,
  AboutUsFaqRoute: AboutUsFaqRoute,
  AboutUsHutRenovationRoute: AboutUsHutRenovationRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  ApiV1ContactRoute: ApiV1ContactRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
